# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - azure-pipelines

pool:
  vmImage: 'macos-latest'

steps:

- script: xcrun simctl list
  displayName: 'Show devices list'

- script: xcrun simctl boot B18FE1B1-475C-4173-ABCF-316536E9D5FE
  displayName: 'Boot simulator'

- script: xcrun simctl bootstatus B18FE1B1-475C-4173-ABCF-316536E9D5FE
  displayName: 'Wait for simulator'

- task: Xcode@5
  displayName: 'Xcode Build'
  inputs:
    actions: 'build'
    scheme: 'TradeDoublerDemo'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcodeVersion: 'default'

- task: Xcode@5
  displayName: 'Xcode UI Tests'
  inputs:
    actions: 'test'
    configuration: 'Debug'
    sdk: 'iphonesimulator'
    scheme: 'TradeDoublerSDKTests'
    destinationTypeOption: 'simulators'
    destinationPlatformOption: 'iOS'
    destinationPlatform: 'iOS Simulator'
    destinationSimulators: 'iPhone 12'
    xcodeVersion: 'default'
    packageApp: false
    useXcpretty: true
    publishJUnitResults: true
